name: Build ZMK firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=ct70_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Rename left firmware
        run: cp build/zephyr/zmk.uf2 ct70_left.uf2
      - name: West Build (Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=ct70_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Rename right firmware
        run: cp build/zephyr/zmk.uf2 ct70_right.uf2
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            ct70_left.uf2
            ct70_right.uf2